### ISSUE TITLE
Comments not working

### ISSUE THREAD

**Issue by aerni** [addisonhall/language-antlers#3]
The comments for the antlers syntax should be {{#  #}}. Instead it is still using regular html comments syntax .

**Comment by addisonhall** [comment]
Yep. I believe I need to work on a settings file:

https://discuss.atom.io/t/add-comment-toggle-to-the-custom-grammar/19733

**Comment by aerni** [comment]
@addisonhall Are you thinking about getting an update out soon?

**Comment by addisonhall** [comment]
I've been meaning to get an update out "soon" for about a year now. ;-)

I'm not making any promises, but I'll try to drop in a settings file before the end of the year.

**Comment by addisonhall** [comment]
Comments should now work! As of 0.3.5.

**Comment by aerni** [comment]
Yes, great! Thanks a lot!
